spring.application.name=springoauth2
spring.security.oauth2.client.registration.google.client-id= 499979174907-9hmk1ppsnhmb8sgf4f58oj7f7tot0mof.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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

spring.security.oauth2.client.registration.github.client-id=Ov23li0Y9932iYh9B80c
spring.security.oauth2.client.registration.github.client-secret=68108f09834ec90e1d18e75d1f6611f94e56e378