spring.application.name=springpractice
spring.config.import=classpath:db.properties

server.port=5080

# Accessing an endpoint
management.endpoint.shutdown.access=unrestricted

# To enable a single points
#management.endpoints.web.exposure.include=health, info

# To enable all the end points
management.endpoints.web.exposure.include=*

# To diasble a single endpoint
#management.endpoint.info.access=none

# To customize the base endpoint
management.endpoints.web.base-path=/spring-actuators

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.orm.jdbc.batch=TRACE


logging.level.org.hibernate.engine.jdbc.batch.internal.BatchingBatch=DEBUG
logging.level.org.hibernate.engine.jdbc.batch.internal.BatchingBatcher=DEBUG



spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver}

spring.jpa.hibernate.ddl-auto=${jpa.ddl}
spring.jpa.show-sql=${jpa.show_sql}
spring.jpa.properties.hibernate.format_sql=${jpa.format_sql}
spring.jpa.database-platform=${jpa.dialect}

spring.jackson.serialization.WRAP_ROOT_VALUE=true
