spring.application.name=empspringdatajpaapp
spring.datasource.url=jdbc:mysql://localhost:3306/dyashin_springboot
spring.datasource.username=root
spring.datasource.password=admin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=9094

logging.level.com.dyashin.empspringdatajpaapp.controller=debug
#logging.level.root=trace
logging.pattern.console= %c : %p --> %m :: %d %n
logging.file.name=logger/log.txt
logging.pattern.file= %d : %c : %p --> %m %M:: %n